class_name AhcEnums
extends RefCounted

## Central enums for Domain / Rules layers (see docs/design/).

enum EntityKind {
	INVESTIGATOR,
	PLAYER_CARD,
	ENEMY,
	LOCATION,
	ACT,
	AGENDA,
	ATTACHMENT,
	SCENARIO_REFERENCE,
	STORY,
}

enum Zone {
	DECK,
	HAND,
	DISCARD,
	SET_ASIDE,
	REMOVED_FROM_GAME,
	VICTORY_DISPLAY,
	PLAY_AREA,
	THREAT_AREA,
	LOCATION_AREA,
	ATTACHED,
	CURRENT_ACT,
	CURRENT_AGENDA,
	SCENARIO_REFERENCE,
	LIMBO,
}

enum CardFace { A, B }

enum SkillType { WILLPOWER, INTELLECT, COMBAT, AGILITY }

enum ChaosTokenKind {
	NUMERIC,
	SKULL,
	CULTIST,
	TABLET,
	ELDER_THING,
	ELDER_SIGN,
	AUTO_FAIL,
	AUTO_SUCCESS,
	BLESS,
	CURSE,
	FROST,
	CAMPAIGN_CUSTOM,
}

enum ActionType {
	DRAW,
	RESOURCE,
	ACTIVATE,
	PLAY,
	MOVE,
	INVESTIGATE,
	ENGAGE,
	EVADE,
	FIGHT,
	PARLEY,
	RESIGN,
}

enum AttackKind { PHASE, OPPORTUNITY, RETALIATE, ALERT }

enum EffectOp {
	DEAL_DAMAGE,
	DEAL_HORROR,
	DEAL_DIRECT_DAMAGE,
	DEAL_DIRECT_HORROR,
	HEAL,
	TRANSFER_AFFLICTION,
	DISCOVER_CLUE,
	PLACE_CLUE,
	SPEND_CLUE,
	GAIN_RESOURCE,
	SPEND_RESOURCE,
	DRAW_CARDS,
	DISCARD_CARDS,
	MOVE_INVESTIGATOR,
	MOVE_ENEMY,
	SPAWN_ENEMY,
	ENGAGE,
	DISENGAGE,
	EVADE_AUTO,
	DEFEAT,
	EXHAUST,
	READY,
	ATTACH,
	ADVANCE_ACT,
	ADVANCE_AGENDA,
	PLACE_DOOM,
	REMOVE_DOOM,
	SEARCH_DECK,
	SHUFFLE,
	EXILE,
	CUSTOM,
}

enum FrameworkStep {
	SETUP_01_CHOOSE_INVESTIGATORS,
	SETUP_02_APPLY_TRAUMA,
	SETUP_03_CHOOSE_LEAD_INVESTIGATOR,
	SETUP_04_SHUFFLE_INVESTIGATOR_DECKS,
	SETUP_05_ASSEMBLE_TOKEN_POOL,
	SETUP_06_ASSEMBLE_CHAOS_BAG,
	SETUP_07_STARTING_RESOURCES,
	SETUP_08_OPENING_HANDS_MULLIGAN,
	SETUP_09_READ_SCENARIO_INTRO,
	SETUP_10_SCENARIO_SETUP,
	SETUP_11_SET_AGENDA_DECK,
	SETUP_12_SET_ACT_DECK,
	SETUP_13_PLACE_SCENARIO_REFERENCE,
	SETUP_14_GAME_BEGINS_ABOUT,
	MYTHOS_1_1_PHASE_BEGINS,
	MYTHOS_1_2_PLACE_DOOM,
	MYTHOS_1_3_CHECK_DOOM_THRESHOLD,
	MYTHOS_1_4_DRAW_ENCOUNTER_EACH,
	MYTHOS_1_5_PHASE_ENDS,
	INV_2_1_PHASE_BEGINS,
	INV_2_2_TURN_BEGINS,
	INV_2_2_1_TAKE_ACTION,
	INV_2_2_2_TURN_ENDS,
	INV_2_3_PHASE_ENDS,
	ENEMY_3_1_PHASE_BEGINS,
	ENEMY_3_2_HUNTER_PATROL_MOVE,
	ENEMY_3_3_ENGAGED_ATTACKS,
	ENEMY_3_4_PHASE_ENDS,
	UPKEEP_4_1_PHASE_BEGINS,
	UPKEEP_4_2_FLIP_MINI_CARDS,
	UPKEEP_4_3_READY_EXHAUSTED,
	UPKEEP_4_4_DRAW_AND_RESOURCE,
	UPKEEP_4_5_CHECK_HAND_SIZE,
	UPKEEP_4_6_PHASE_ENDS,
	SCENARIO_RESOLUTION,
	GAME_OVER,
}

enum SkillTestStep {
	ST_1_BEGIN,
	ST_2_COMMIT,
	ST_3_REVEAL,
	ST_4_SYMBOL,
	ST_5_CALCULATE,
	ST_6_RESOLVE_RESULT,
	ST_7_APPLY,
	ST_8_END,
}

enum InitiationStep {
	INIT_PRE_RESTRICTIONS,
	INIT_1_APPLY_MODIFIERS,
	INIT_2_PAY_COSTS,
	INIT_2B_AOO,
	INIT_3_COMMENCE,
	INIT_4_RESOLVE,
}

enum ChoiceKind {
	USE_ABILITY,
	OPTIONAL_EFFECT,
	ORDER_SIMULTANEOUS,
	PICK_TARGET,
	PICK_MULTI,
	PICK_OPTION,
	ASSIGN_DAMAGE,
	ASSIGN_HORROR,
	ORDER_CARDS,
	ORDER_PLAYER,
	ORDER_ATTACKS,
	PLAY_CARD,
	ACTIVATE_ABILITY,
	COMMIT_TO_TEST,
	PAY_COST,
	PAY_X,
	SEARCH_TAKE,
	DISCARD_SELECT,
	CHAOS_PICK,
	INSTEAD_PICK,
	CHOOSE_TRAUMA,
	SETUP_CHOICE,
	CAMPAIGN_DECISION,
	CONFIRM_STEP,
	SILVER_RULE,
	TIE_BREAK,
}

enum PlayerWindow {
	PW_MYTHOS_AFTER_BEGIN,
	PW_MYTHOS_AFTER_ENCOUNTER_DRAW,
	PW_MYTHOS_BEFORE_END,
	PW_INV_AFTER_PHASE_BEGIN,
	PW_INV_BEFORE_ACTION,
	PW_INV_AFTER_ACTION,
	PW_INV_BEFORE_TURN_END,
	PW_ENEMY_AFTER_MOVE,
	PW_ENEMY_BETWEEN_ATTACKS,
	PW_UPKEEP_AFTER_READY,
	PW_SKILL_TEST_AFTER_COMMIT,
	PW_SKILL_TEST_AFTER_REVEAL,
}

enum LogCategory {
	SYSTEM,
	FRAMEWORK,
	ACTION,
	ABILITY,
	SKILL_TEST,
	DAMAGE,
	CARD,
	SCENARIO,
}

enum FaceAudience { HIDDEN_ALL, CONTROLLER, ALL }

enum GrimRuleMode { AUTO_WORST, PAUSE_FOR_RULING, DISABLED }

enum EventRecordKind {
	FRAMEWORK_STEP,
	INITIATION_STEP,
	SKILL_TEST_STEP,
	EFFECT_APPLIED,
	COMPOSITION_STEP,
	SEQUENCE_STEP,
	SYSTEM,
	TURN_BEGIN,
	TURN_END,
	ACTION_SPEND,
	ACTION_SPEND_VOID,
	ACTION_GRANT,
}

enum StatKey {
	TURN_ACTION_SPEND_COUNT,
	TURN_ACTION_SPEND_EMPTY,
}

enum StatCompareOp { EQ, GE, LE }

enum SequencePhase { WHEN, RESOLVE, AFTER }

enum PileKind {
	INV_DECK,
	INV_HAND,
	INV_DISCARD,
}

enum InsertMode { TOP, BOTTOM }

enum MarkerKind {
	DAMAGE,
	HORROR,
	DOOM,
	CLUE,
	RESOURCE,
	HORROR_TAKEN,
	POOL_DAMAGE,
	POOL_HORROR,
	POOL_CLUE,
	POOL_RESOURCE,
}

enum BearerKind { CARD, INVESTIGATOR, GLOBAL }

enum AtomOp { MOVE_CARD, TRANSFER_MARKER, ADJUST_MARKER, REVEAL_CARD, SET_FLAG, SET_REF }

enum FlagField { ELIMINATED }

enum RestrictionKind {
	FORBID_DRAW,
	FORBID_PLAY,
	FORBID_TRIGGER,
	FORBID_COMMIT_TO_TEST,
	FORBID_LEAVE_HAND,
}

enum BuffType { MODIFIER, RESTRICTION, LISTENER, KEYWORD }

enum CompositionNodeKind { SEQ, ATOM, REGISTER, IF }

enum LifetimeKind {
	WHILE_IN_PLAY,
	DURATION,
	UNTIL_FIRED,
	WHILE_ENCOUNTER_FRAME,
	WHILE_DRAWN_CARD_RESOLVING,
	WHILE_HIDDEN_IN_HAND,
}

enum DurationAnchorKind { THIS_TURN, THIS_PHASE, THIS_SKILL_TEST, THIS_ROUND }

enum StatRef {
	SKILL_WILLPOWER,
	SKILL_INTELLECT,
	SKILL_COMBAT,
	SKILL_AGILITY,
	RESOURCE_GAIN_AMOUNT,
	INITIATION_RESOURCE_COST,
	INITIATION_ACTION_COST,
}

enum ModOp { ADD, SUB, MUL, DOUBLE, HALVE }
